# The root route with all parameters, which are inherited by the child
# routes if they are not overwritten.
route:
  # Base alert receiver (is a fallback is none was matched)
  receiver: discord
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  # All alerts that do not match the following child routes
  # will remain at the root node and be dispatched to 'default-receiver'.
  routes:
  # Telegram alert channel, business or critical alerts (continue true to continue route matching)
  - receiver: telegram_receiver
    matchers:
    - severity =~ "telegram_alert|critical"
    continue: true
  # Infrastrcuture alert channel, infrastructure alerts (continue true to continue route matching)
  - receiver: discord_infrastructure_receiver
    matchers:
    - category =~ "infrastructure"
    continue: true

receivers:
  - name: discord
    discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1117499416056705175/ihfuGM9SqpFGvb5LudiGU_eIeS6Xsozemd5m99UIjSxa8Ij1ZjlbNvBnvrmuc5i2vywK
  - name: discord_infrastructure_receiver
    discord_configs:
      - webhook_url: https://discord.com/api/webhooks/1123403200909819964/9ejrMSvlZc8RW-3aODMqS_1yV1RsrqU8Zo2jSpU5lTo2bjaN6c8Z6rhT2bFrVTFaKNmF
  - name: telegram_receiver
    telegram_configs:
      - bot_token: 5940031294:AAEGTKK56YWH__cAfL_wy7nLrsdpg-CaePs
        api_url: https://api.telegram.org
        chat_id: -986827899
        message: |
            {{ if eq .Status "firing" }}🔥 {{ end }}{{ if eq .Status "resolved" }}✅ {{ end }}[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}
            
            <b>Alert:</b> {{ .CommonLabels.alertname }}
            {{ range .Alerts }}{{ if .Labels.severity }}<b>Severity:</b> {{ .Labels.severity | toUpper }}{{ end }}
            {{ if .Annotations.summary }}<b>Summary:</b> {{ .Annotations.summary }}{{ end }}
            {{ if .Annotations.description }}<b>Description:</b> {{ .Annotations.description }}{{ end }}
            <b>Details:</b>
                  {{ range .Labels.SortedPairs }}- {{ .Name }}: <i>{{ .Value }}</i>
                  {{ end }}
            {{ end }}
