{
 "title": "App metrics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cantidad de Requests ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{job=\"weather-metrics-component\"}) - sum(http_request_duration_seconds_count{job=\"weather-metrics-component\"} offset 2m)",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Apdex Score (respuesta <= 30ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.5\"}[2m])) by (job) +\n  (\n    sum(rate(http_request_duration_seconds_bucket{le=\"1\"}[2m])) by (job) - \n    sum(rate(http_request_duration_seconds_bucket{le=\"0.5\"}[2m])) by (job)\n  ) / 2\n) / \nsum(rate(http_request_duration_seconds_count[2m])) by (job)\n",
     "legendFormat": "Tiempo de respuesta"
    }
   ]
  },
  {
   "title": "% Requests respondidos por tiempo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"5\"}[5m])) by (job)\n  - sum(rate(http_request_duration_seconds_bucket{le=\"1\"}[5m])) by (job)\n) \n/\nsum(rate(http_request_duration_seconds_count[5m])) by (job) * 100",
     "legendFormat": "< 5 seg"
    },
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"1\"}[5m])) by (job)\n  - sum(rate(http_request_duration_seconds_bucket{le=\"0.5\"}[5m])) by (job)\n) \n/\nsum(rate(http_request_duration_seconds_count[5m])) by (job) * 100",
     "legendFormat": "< 1 seg"
    },
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.5\"}[5m])) by (job)\n  - sum(rate(http_request_duration_seconds_bucket{le=\"0.3\"}[5m])) by (job)\n) \n/\nsum(rate(http_request_duration_seconds_count[5m])) by (job) * 100",
     "legendFormat": "< 0.5 seg"
    },
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.3\"}[5m])) by (job)\n  - sum(rate(http_request_duration_seconds_bucket{le=\"0.05\"}[5m])) by (job)\n) \n/\nsum(rate(http_request_duration_seconds_count[5m])) by (job) * 100",
     "legendFormat": "< 0.3 seg"
    },
    {
     "expr": "  sum(rate(http_request_duration_seconds_bucket{le=\"0.05\"}[5m])) by (job)\n/\n  sum(rate(http_request_duration_seconds_count[5m])) by (job) * 100",
     "legendFormat": "< 0.03 seg"
    }
   ]
  },
  {
   "title": "Tiempo de Respuesta promedio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\n  rate(http_request_duration_seconds_sum[2m])\n  /\n  rate(http_request_duration_seconds_count[2m])\n)",
     "legendFormat": "Promedio de tiempo"
    }
   ]
  },
  {
   "title": "% Requests respondidos por tiempo",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"5\"}[5m])) by (job)\n  - sum(rate(http_request_duration_seconds_bucket{le=\"1\"}[5m])) by (job)\n) \n/\nsum(rate(http_request_duration_seconds_count[5m])) by (job) * 100",
     "legendFormat": "< 5 seg"
    },
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"1\"}[5m])) by (job)\n  - sum(rate(http_request_duration_seconds_bucket{le=\"0.5\"}[5m])) by (job)\n) \n/\nsum(rate(http_request_duration_seconds_count[5m])) by (job) * 100",
     "legendFormat": "< 1 seg"
    },
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.5\"}[5m])) by (job)\n  - sum(rate(http_request_duration_seconds_bucket{le=\"0.3\"}[5m])) by (job)\n) \n/\nsum(rate(http_request_duration_seconds_count[5m])) by (job) * 100",
     "legendFormat": "< 0.5 seg"
    },
    {
     "expr": "(\n  sum(rate(http_request_duration_seconds_bucket{le=\"0.3\"}[5m])) by (job)\n  - sum(rate(http_request_duration_seconds_bucket{le=\"0.05\"}[5m])) by (job)\n) \n/\nsum(rate(http_request_duration_seconds_count[5m])) by (job) * 100",
     "legendFormat": "< 0.3 seg"
    },
    {
     "expr": "  sum(rate(http_request_duration_seconds_bucket{le=\"0.05\"}[5m])) by (job)\n/\n  sum(rate(http_request_duration_seconds_count[5m])) by (job) * 100",
     "legendFormat": "< 0.03 seg"
    }
   ]
  }
 ]
}